# Адрес и порт сервера
addr: "0.0.0.0:8082"

# Путь к файлу логов
log_file: "app.log"

# Адрес микросервиса Notifier(через Docker)
notifier_url: "http://notifier:8081"

# Размер буфера каналов (логгер и очередь уведомлений)
buffer_size: 200

# Как часто запускать горутину чистки
interval: "1m"

# Через какое время событие считается старым и уходит в архив
archive_after: "24h"